---
- hosts: unsubscribe
  remote_user: admin

  tasks:
    - name: pull from git
      git:
        repo: git@github.com:robertkanyur/fairway-unsubscribe-dev.git
        dest: /home/admin/unsubscribe
        update: yes
        version: master
    - name: build assets
      docker_service:
        project_src: /home/admin/unsubscribe/assets
    - name: update containers
      docker_service:
        project_src: /home/admin/unsubscribe
