---
- hosts: unsubscribe
  remote_user: admin

  tasks:
    - name: pull from git
      git:
        repo: git@github.com:robertkanyur/fairway-unsubscribe-dev.git
        dest: /home/admin/unsubscribe
        update: yes
        version: master
    - name: build assets and restart containers
      docker_service:
        project_src: /home/admin/unsubscribe/assets
      notify:
        - restart containers
  handlers:
    - name: containers down
      docker_service:
          project_src: /home/admin/unsubscribe
          state: absent
          listen: "restart containers"
    - name: containers up
      docker_service:
          project_src: /home/admin/unsubscribe
          state: present
          listen: "restart containers"

