---
- hosts: unsubscribe
  remote_user: admin

  tasks:
    - name: pull from git
      git:
        repo: git@github.com:robertkanyur/fairway-unsubscribe-dev.git
        dest: /home/admin/unsubscribe
        update: yes
        version: master
    - name: rebuild unsubscribe-web image if necessary
      docker_image:
        name: unsubscribe-web
        path: /home/admin/unsubscribe
    - name: rebuild unsubscribe-assets image if necessary
      docker_image:
        name: unsubscribe-assets
        path: /home/admin/unsubscribe/assets
    - name: start building assets
      docker_service:
        project_src: /home/admin/unsubscribe/assets
      register: output
    - name: wait for assets to build
      wait_for:
        port: 2992
        state: stopped
    - name: docker containers down
      docker_service:
          project_src: /home/admin/unsubscribe
          state: absent
    - name: docker containers up
      docker_service:
          project_src: /home/admin/unsubscribe
          state: present
    - name: check web server is responding
      uri:
        url: https://unsubscribe.fairway321.com
        status_code: 200
      retries: 12
      delay: 5
      register: response
      until: response.status == 200
      changed_when: False
