---
- hosts: unsubscribe
  remote_user: admin

  tasks:
    - name: pull from git
      git:
        repo: git@github.com:robertkanyur/fairway-unsubscribe-dev.git
        dest: /home/admin/unsubscribe
        update: yes
        version: master
    - name: start building assets
      docker_service:
        project_src: /home/admin/unsubscribe/assets
      register: output
    - name: wait for assets to build
      wait_for:
        port: 2992
    - name: docker containers down
      docker_service:
          project_src: /home/admin/unsubscribe
          state: absent
    - name: docker containers up
      docker_service:
          project_src: /home/admin/unsubscribe
          state: present
    - name: check web server is responding
      wait_for:
        port: 5000

