version: '2'

services:
  web:
    restart: always
    image: unsubscribe-web
    networks:
      - proxy_default
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./src:/home/unsubscribe/src
    expose:
      - 5000
    ports:
      - '5000:5000'
    entrypoint: ["./boot.sh"]
    environment:
      - FLASK_APP
      - FLASK_ENV
      - CONSUMER_KEY
      - CONSUMER_SECRET
      - SF_USERNAME
      - SF_PASSWORD
      - SF_SECURITY_TOKEN
      - SF_ACCESS_TOKEN
      - SF_INSTANCE_URL
      - SLACK_BOT_TOKEN
      - TEMPLATES_AUTO_RELOAD
      - DATABASE_URL
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - DEBUG
      - SENTRY_DSN
  db:
    image: mysql:5.7
    networks:
      - proxy_default
    restart: always
    environment:
      MYSQL_DATABASE: unsubscribe
      MYSQL_USER: unsubscribe
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    volumes:
      - unsubscribe_db:/var/lib/mysql

volumes:
  unsubscribe_db:
    external: true

networks:
  proxy_default:
    external: true
