version: '2'

services:
  web:
    restart: always
    image: unsubscribe-web
    build:
      context: .
      dockerfile: Dockerfile-web
    expose:
      - 5000
    environment:
      - FLASK_APP
      - FLASK_ENV
      - CONSUMER_KEY
      - CONSUMER_SECRET
      - SF_USERNAME
      - SF_PASSWORD
      - SF_SECURITY_TOKEN
      - SF_ACCESS_TOKEN
      - SF_INSTANCE_URL
      - SLACK_BOT_TOKEN
      - TEMPLATES_AUTO_RELOAD
      - DATABASE_URL
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - DEBUG
  assets:
    restart: always
    image: unsubscribe-assets
    build:
      context: .
      dockerfile: Dockerfile-assets
    expose:
      - 2992
    ports:
      - "2992:80"
    depends_on:
      - web
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: unsubscribe
      MYSQL_USER: unsubscribe
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - web
    expose:
      - "3306"
    volumes:
      - unsubscribe_db:/var/lib/mysql
  proxy:
    image: unsubscribe-proxy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-proxy
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  unsubscribe_db:
    external: true
