version: '2'

services:
  web:
    restart: always
    image: unsubscribe
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./app:/home/unsubscribe/app
      - ./migrations:/home/unsubscribe/migrations
      - ./assets:/home/unsubscribe/assets
      - ./build:/home/unsubscribe/build
    expose:
      - 5000
    environment:
      - FLASK_APP
      - FLASK_ENV
      - CONSUMER_KEY
      - CONSUMER_SECRET
      - SF_USERNAME
      - SF_PASSWORD
      - SF_SECURITY_TOKEN
      - SF_ACCESS_TOKEN
      - SF_INSTANCE_URL
      - SLACK_BOT_TOKEN
      - TEMPLATES_AUTO_RELOAD
      - DATABASE_URL
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - DEBUG
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: unsubscribe
      MYSQL_USER: unsubscribe
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    volumes:
      - unsubscribe_db:/var/lib/mysql
  proxy:
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/proxy:/etc/nginx/conf.d
      - ./conf/certbot/conf:/etc/letsencrypt
      - ./conf/certbot/www:/var/www/certbot
      - ./build/public:/var/www/public
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./conf/certbot/conf:/etc/letsencrypt
      - ./conf/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  unsubscribe_db:
    external: true
