version: '2'

services:
  web:
    restart: always
    image: unsubscribe-web
    depends_on:
      - assets
    build:
      context: .
    volumes:
      - ./src:/home/unsubscribe/src
    expose:
      - 5000
    ports:
      - "5000:5000"
    entrypoint: ["./boot.dev.sh"]
    environment:
      - FLASK_APP
      - FLASK_ENV
      - CONSUMER_KEY
      - CONSUMER_SECRET
      - SF_USERNAME
      - SF_PASSWORD
      - SF_SECURITY_TOKEN
      - SF_ACCESS_TOKEN
      - SF_INSTANCE_URL
      - SLACK_BOT_TOKEN
      - TEMPLATES_AUTO_RELOAD
      - DEBUG
  assets:
    restart: always
    image: unsubscribe-assets
    build:
      context: .
      dockerfile: assets/Dockerfile
    volumes:
      - ./src:/home/node/src
    expose:
      - 2992
    ports:
      - "2992:2992"
    entrypoint: ["./assets.dev.sh"]
