"""unsubscribe table

Revision ID: 10521243fcac
Revises: 
Create Date: 2019-04-14 02:27:25.433772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10521243fcac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unsubscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unsubscribe_address'), 'unsubscribe', ['address'], unique=False)
    op.create_index(op.f('ix_unsubscribe_email'), 'unsubscribe', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unsubscribe_email'), table_name='unsubscribe')
    op.drop_index(op.f('ix_unsubscribe_address'), table_name='unsubscribe')
    op.drop_table('unsubscribe')
    # ### end Alembic commands ###
