"""added sf_response to unsubscribe

Revision ID: 57e026f8358f
Revises: 3a1ea974b2fb
Create Date: 2019-04-14 19:56:17.192603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e026f8358f'
down_revision = '3a1ea974b2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unsubscribe', sa.Column('sf_response', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_unsubscribe_sf_response'), 'unsubscribe', ['sf_response'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unsubscribe_sf_response'), table_name='unsubscribe')
    op.drop_column('unsubscribe', 'sf_response')
    # ### end Alembic commands ###
