"""remove indexes, add previously

Revision ID: 89306c841ec4
Revises: 57e026f8358f
Create Date: 2019-04-14 20:20:47.278634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89306c841ec4'
down_revision = '57e026f8358f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unsubscribe', sa.Column('previously', sa.Boolean(), nullable=True))
    op.drop_index('ix_unsubscribe_address', table_name='unsubscribe')
    op.drop_index('ix_unsubscribe_sf_response', table_name='unsubscribe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unsubscribe_sf_response', 'unsubscribe', ['sf_response'], unique=False)
    op.create_index('ix_unsubscribe_address', 'unsubscribe', ['address'], unique=False)
    op.drop_column('unsubscribe', 'previously')
    # ### end Alembic commands ###
