version: '2'

services:
  build:
    image: unsubscribe-assets
    ports:
      - "2992:2992"
    build:
      context: ../
    volumes:
      - ../src:/home/node/src
    entrypoint: ["./assets.sh"]

